a=input('Enter first number:')
b=input('Enter second number:')
a=int(a)
b=int(b)
c=(a+b)
d=(a-b)
e=(a*b)
f=(a%b)
print('The average value of a and b is:',c)
print('The avg value of a and b is:',d)
print('The avg value of a and b is:',e)
print('The avg value of a and b is:',f)
